src/WebApp/Models/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class SearchFormViewModel
    {
        [Display(Name = "Color")]
        public string color { get; set; }
        [Display(Name = "Keywords")]
        public string keywords { get; set; }
    }
}

src/WebApp/ViewModels/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;

namespace WebApp.ViewModels
{
    public class SearchViewModel
    {
        public string SearchColor { get; set; }
        public string ColorName { get; set; }
        public string SearchKeywords { get; set; }
        public int ArtistID { get; set; }
        public int CurrentPage { get; set; }
        public long? FoundCount { get; set; }
        public List<ProductSearchResult> Results { get; set; }

    }
}

src/WebApp/Controllers/ArtPrintsController.cs
using ColorMine.ColorSpaces;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text.RegularExpressions;
using WebApp.Models;
using WebApp.Services;
using WebApp.Services.Utilities;

namespace WebApp.Controllers
{
    public class ArtPrintsController : Controller
    {
        private ArtByHueContext _context;
        private TelemetryClient telemetry = new TelemetryClient();

        public ArtPrintsController(ArtByHueContext context)
        {
            _context = context;
        }

        [Route("{id:int}/{name?}")]
        public IActionResult Index(int id, string name = "", int searchPage = 0, string searchColor = "", string searchKeywords = "")
        {
            var prod = _context.Products.Include(x => x.Artist).Include(x => x.Supplier).Include(x => x.Images).Include(x => x.Colors).FirstOrDefault(x => x.ProductID == id);

            if (prod == null)
            {
                return View("CustomError", "That product appears to be missing.");
            }
            var paintMatches = new List<ColorLookup>();
            var paintMatchesRGB = new List<MatchedPaint>();

            var cie = new ColorMine.ColorSpaces.Comparisons.Cie1976Comparison();
            if (prod?.Colors != null)
            {
                foreach (var color in prod.Colors)
                {
                    foreach (var paint in ColorName.PaintColors.Where(x => !x.name.ToLower().Contains("pantone")))
                    {
                        var picColorRgb = new Rgb { R = color.R, G = color.G, B = color.B };
                        var picColorLab = picColorRgb.To<Lab>();

                        var paintColor = ProductSearch.ConvertHex(paint.hex.Replace("#", ""));

                        var paintColorRgb = new Rgb { R = paintColor.R, G = paintColor.G, B = paintColor.B };
                        var paintColorLab = paintColorRgb.To<Lab>();

                        var diff = cie.Compare(picColorLab, paintColorRgb);
                        if (diff < 2.2)
                        {
                            var manf = paint.name.Substring(paint.name.IndexOf('('), paint.name.IndexOf(')') - paint.name.IndexOf('('));
                            if (!paintMatchesRGB.Exists(x => x.Manufacturer == manf && x.Name == paint.name))
                            //(x.RGB.R == paintColorRgb.R) &&
                            //(x.RGB.G == paintColorRgb.G &&
                            //(x.RGB.B == paintColorRgb.B))))
                            {
                                paintMatchesRGB.Add(new Models.MatchedPaint { Manufacturer = manf, RGB = paintColorRgb, Name = paint.name });
                                paintMatches.Add(paint);
                            }
                        }
                    }
                }

            }
            var vm = new ProductViewModel
            {
                SearchPage = searchPage,
                SearchColor = searchColor,
                SearchKeywords = searchKeywords,
                Product = prod,
                MatchingPaints = paintMatches
            };

            var title = prod.Title + " " + (prod.Artist != null && !String.IsNullOrEmpty(prod.Artist.Name) ? prod.Artist.Name : "");
            ViewBag.CanonicalURL = String.Format("{0}/{1}/{2}", Request.Scheme + "://" + Request.Host, id, Slug.Create(true, title));

            ViewBag.IsCurator = Request.Cookies["ABHCurator"] != null ? Request.Cookies["ABHCurator"] : "0";

            return View(vm);
        }

        [HttpGet]
        [Produces("application/json")]
        public ActionResult ProductDetail(int id)
        {
            var prod = _context.Products.Include(x => x.Artist).Include(x => x.Supplier).Include(x => x.Images).Include(x => x.Colors).FirstOrDefault(x => x.ProductID == id);
            if (prod == null)
            {
                return NotFound();
            }

            //circular reference messing up json
            foreach (var i in prod.Images)
            {
                i.Product = null;
            }

            foreach (var c in prod.Colors)
            {
                c.Product = null;
            }

            var result = new JsonResult(prod);
            return result;
        }

        [Route("search/{color?}/{keywords?}/{page:int?}")]
        public IActionResult Search(string color = "", string keywords = "", int page = 1, string colorName = "")
        {
            page = page == 0 ? 1 : page;

            if (color?.Trim() != "" && (keywords == null || keywords?.Trim() == ""))
            {
                return Redirect(String.Format("/color/{0}/{1}/{2}", color, Slug.Create(true, colorName), page));
            }
            else if (!String.IsNullOrEmpty(keywords) && (String.IsNullOrEmpty(color) || color.Replace("#", "").ToLower() == "ffffff"))
            {
                return RedirectToAction("Category", new { name = Slug.Create(true, keywords) });
            }
            var prods = ProductSearch.GetForCriteria(_context, page - 1, keywords, color);
            prods.ColorName = colorName;
            prods.CurrentPage = page;
            prods.SearchColor = color;
            prods.SearchKeywords = keywords;

            var newEvent = new EventTelemetry();
            newEvent.Name = "SearchColorAndKeywords";
            newEvent.Properties["color"] = color;
            newEvent.Properties["color-name"] = colorName;
            newEvent.Properties["keywords"] = keywords;
            newEvent.Properties["page"] = page.ToString();
            newEvent.Properties["result-count"] = prods.FoundCount.ToString();

            telemetry.TrackEvent(newEvent);

            if (prods.FoundCount == -1)
            {
                return View("CustomError", "Records not available");
            }

            ViewBag.IsCurator = Request.Cookies["ABHCurator"] != null ? Request.Cookies["ABHCurator"] : "0";

            return View(prods);
        }

        public PartialViewResult _NextResults(string query, int page)
        {
            var prods = ProductSearch.GetForCriteria(_context, page, "red", "C3BA97");

            return PartialView(prods);
        }

        [Route("artist/{id:int}/{name?}/{page?}")]
        public IActionResult Artist(int id, string name = "", int page = 1)
        {
            page = page == 0 ? 1 : page;
            var prods = ProductSearch.GetForArtist(_context, id, page - 1);
            prods.CurrentPage = page;
            var artistName = ProductSearch.ArtistNameLookup(_context, id);
            prods.SearchKeywords = artistName;

            var newEvent = new EventTelemetry();
            newEvent.Name = "GetArtistProducts";
            newEvent.Properties["artist-id"] = id.ToString();
            newEvent.Properties["name"] = artistName;
            newEvent.Properties["page"] = page.ToString();
            newEvent.Properties["result-count"] = prods.FoundCount.ToString();

            telemetry.TrackEvent(newEvent);

            ViewBag.IsArtist = true;
            ViewBag.CanonicalURL = String.Format("{0}/artist/{1}/{2}/{3}", Request.Scheme + "://" + Request.Host, id, Slug.Create(true, artistName), page);
            ViewBag.IsCurator = Request.Cookies["ABHCurator"] != null ? Request.Cookies["ABHCurator"] : "0";
            return View(prods);
        }

        [Route("{name}/{page:int?}")]
        public IActionResult Category(string name, int page = 1)
        {
            Char[] arr = { '!', '@' };
            name = System.Net.WebUtility.HtmlDecode(name);

            Regex regex = new Regex(@"^[A-Za-z\d_-]+$");
            Match match = regex.Match(name);
            if (!match.Success)
            {
                return new StatusCodeResult(403);
            }
            page = page == 0 ? 1 : page;
            var prods = ProductSearch.GetForCriteria(_context, page - 1, name.Replace("-", " "), "");
            prods.CurrentPage = page;
            prods.SearchKeywords = name.Replace("-", " ");

            var newEvent = new EventTelemetry();
            newEvent.Name = "KeywordOnlySearch";
            newEvent.Properties["keywords"] = name.Replace("-", " ");
            newEvent.Properties["page"] = page.ToString();
            newEvent.Properties["result-count"] = prods.FoundCount.ToString();

            telemetry.TrackEvent(newEvent);
            ViewBag.CanonicalURL = String.Format("{0}/{1}/{2}", Request.Scheme + "://" + Request.Host, name, page);
            if (prods.FoundCount == -1)
            {
                return View("CustomError", "Records not available");
            }

            ViewBag.IsCurator = Request.Cookies["ABHCurator"] != null ? Request.Cookies["ABHCurator"] : "0";

            return View(prods);
        }

        [Route("color/{colorHex}/{colorName?}/{page:int?}")]
        public IActionResult ColorOnly(string colorHex, string colorName = "", int page = 1)
        {
            page = page == 0 ? 1 : page;
            colorHex = colorHex?.Replace("#", "");
            var prods = ProductSearch.GetForCriteria(_context, page - 1, "", colorHex);
            prods.CurrentPage = page;
            prods.SearchColor = colorHex;
            prods.SearchKeywords = "";
            prods.ColorName = ColorName.SlugLookup().ContainsKey(colorName) ? ColorName.SlugLookup()[colorName] : colorName.Replace("-", " ");

            var newEvent = new EventTelemetry();
            newEvent.Name = "ColorOnlySearch";
            newEvent.Properties["color"] = colorHex;
            newEvent.Properties["color-name"] = prods.ColorName;
            newEvent.Properties["page"] = page.ToString();
            newEvent.Properties["result-count"] = prods.FoundCount.ToString();

            telemetry.TrackEvent(newEvent);

src/WebApp/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Models;
using WebApp.ViewModels;
using Microsoft.Azure.Search;
using Microsoft.Azure.Search.Models;
using WebApp.Services;

namespace WebApp.Controllers
{
    public class SearchController : Controller
    {
        private ArtByHueContext _context;

        public SearchController(ArtByHueContext context)
        {
            _context = context;
        }

        public IActionResult Index(string color = "", string keywords = "", int page = 1)
        {
            var prods = ProductSearch.GetForCriteria(_context, page - 1, keywords, color);
            prods.CurrentPage = page;
            return View(prods);
        }

        public PartialViewResult _NextResults (string query, int page)
        {
            var prods = ProductSearch.GetForCriteria(_context, page, "red", "C3BA97");

            return PartialView(prods);
        }
    }
}

src/WebApp/Views/ArtPrints/Artist.cshtml
@model WebApp.ViewModels.SearchViewModel
@using WebApp.Services.Utilities

@{
    var pageCount = (Model.FoundCount + 30 - 1) / 30;
    ViewData["Title"] = "Art Prints By " + Model.Results[0].Artist;
    ViewData["PageTitle"] = "Art Prints By " + Model.Results[0].Artist;
    ViewData["PageDesc"] = Model.Results[0].Artist + " makes these art prints available at the suppliers displayed.";
    ViewData["Type"] = "product.group";

    var images = new List<string>();

    foreach (var r in Model.Results)
    {
        images.Add(r.LargeImageURL);
    }

    var slug = Slug.Create(true, Model.SearchKeywords);
    ViewData["Images"] = images;
}

@*@if (!String.IsNullOrEmpty(Model.BackToAction))
    {
        <div>
            <a asp-controller="ArtPrints" asp-action="@Model.BackToAction" asp-route-page="@Model.CurrentPage" asp-route-color="@Model.SearchColor" asp-route-keywords="@Model.SearchKeywords">Back to List</a>
        </div>
    }*@
@Html.Partial("_ResultsHeader")

@{ await Html.RenderPartialAsync("_Products", Model.Results); }

@*<div id="results"></div>
    <button id="get-more">Load More</button>
    <a asp-controller="Search" asp-action="Index" asp-route-keywords="@Model.SearchKeywords" asp-route-color="@Model.SearchColor" asp-route-page="@(Model.CurrentPage + 1)">Next Page</a>*@

@if (Model.FoundCount > 30)
{
    <div class="row">
        <div class="col-xs-12 col-md-6 col-xl-4">
            @if (Model.CurrentPage != 1)
            {
                <div class="card next-page-card">
                    <a class="next-page" asp-controller="ArtPrints" asp-action="Artist" asp-route-artistid="@Model" asp-route-page="@(Model.CurrentPage - 1)" aria-label="Previous"><i class="fa fa-chevron-left left"></i> Previous Page</a>
                </div>
            }
        </div>
        <div class="col-xs-12 col-md-6 col-xl-4 col-xl-offset-4">
            @if (Model.CurrentPage != pageCount)
            {
                <div class="card next-page-card">
                    <a class="next-page" asp-controller="ArtPrints" asp-action="Artist" asp-route-name="@slug" asp-route-page="@(Model.CurrentPage + 1)" aria-label="Next">Next Page <i class="fa fa-chevron-right right"></i></a>
                </div>
            }
        </div>
    </div>
    <nav class="pager-bottom">
        <div style="width: 100%; text-align: center; margin-bottom: -10px;">Jump to Page </div>
        <ul class="pagination pagination-lg">
            @for (int i = 1; i <= pageCount && i < 3335; i++)
            {
                <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                    <a class="page-link" asp-controller="ArtPrints" asp-action="Artist" asp-route-name="@slug" asp-route-page="@i" aria-label="Page @i">@i</a>
                </li>
            }
        </ul>
    </nav>
}
<div class="clearfix"></div>
@Html.Partial("_Ads")
<div class="p-a-3">
    <a data-sumome-discover-grid></a>
</div>
@section scripts
{
    @Html.Partial("_ProductsScripts");

    @*<script>
            var nextPage = 2;
            $(function () {
                $("#get-more").click(function () {
                    $.get("/Search/_NextResults",
                    {
                        query: '',
                        page: nextPage
                    }, function (data) {
                        $('#results').append(data);
                        nextPage++;
                    })

                });
            })
        </script>*@

}

src/WebApp/Views/ArtPrints/Category.cshtml
@model WebApp.ViewModels.SearchViewModel
@using WebApp.Services.Utilities
@{
    var pageCount = (Model.FoundCount + 30 - 1) / 30;
    ViewData["Title"] = Model.SearchKeywords + " Art Prints";
    ViewData["PageTitle"] = Model.SearchKeywords + " Art Prints";
    ViewData["PageDesc"] = "Art Prints for the category '" + Model.SearchKeywords + "'";
    ViewData["Type"] = "product.group";

    var images = new List<string>();

    foreach (var r in Model.Results)
    {
        images.Add(r.LargeImageURL);
    }

    var slug = Slug.Create(true, Model.SearchKeywords);
    ViewData["Images"] = images;
}

@*@if (!String.IsNullOrEmpty(Model.BackToAction))
    {
        <div>
            <a asp-controller="ArtPrints" asp-action="@Model.BackToAction" asp-route-page="@Model.CurrentPage" asp-route-color="@Model.SearchColor" asp-route-keywords="@Model.SearchKeywords">Back to List</a>
        </div>
    }*@
@Html.Partial("_ResultsHeader")

@{ await Html.RenderPartialAsync("_Products", Model.Results); }

@*<div id="results"></div>
    <button id="get-more">Load More</button>
    <a asp-controller="Search" asp-action="Index" asp-route-keywords="@Model.SearchKeywords" asp-route-color="@Model.SearchColor" asp-route-page="@(Model.CurrentPage + 1)">Next Page</a>*@

@if (Model.FoundCount > 30)
{
    <div class="row">
        <div class="col-xs-12 col-md-6 col-xl-4">
            @if (Model.CurrentPage != 1)
            {
                <div class="card next-page-card">
                    <a class="next-page" asp-controller="ArtPrints" asp-action="Category" asp-route-name="@slug" asp-route-page="@(Model.CurrentPage - 1)" aria-label="Previous"><i class="fa fa-chevron-left left"></i> Previous Page</a>
                </div>
            }
        </div>
        <div class="col-xs-12 col-md-6 col-xl-4 col-xl-offset-4">
            @if (Model.CurrentPage != pageCount)
            {
                <div class="card next-page-card">
                    <a class="next-page" asp-controller="ArtPrints" asp-action="Category" asp-route-name="@slug" asp-route-page="@(Model.CurrentPage + 1)" aria-label="Next">Next Page <i class="fa fa-chevron-right right"></i></a>
                </div>
            }
        </div>
    </div>
    <nav class="pager-bottom">
        <div style="width: 100%; text-align: center; margin-bottom: -10px;">Jump to Page </div>
        <ul class="pagination pagination-lg">
            @for (int i = 1; i <= pageCount && i < 3335; i++)
            {
                <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                    <a class="page-link" asp-controller="ArtPrints" asp-action="Category" asp-route-name="@slug" asp-route-page="@i" aria-label="Page @i">@i</a>
                </li>
            }
        </ul>
    </nav>
}
<div class="clearfix"></div>
@Html.Partial("_Ads")
<div class="p-a-3">
    <a data-sumome-discover-grid></a>
</div>

@section scripts
{
    @Html.Partial("_ProductsScripts");
    @*<script>
            var nextPage = 2;
            $(function () {
                $("#get-more").click(function () {
                    $.get("/Search/_NextResults",
                    {
                        query: '',
                        page: nextPage
                    }, function (data) {
                        $('#results').append(data);
                        nextPage++;
                    })

                });
            })
        </script>*@

}

src/WebApp/Views/ArtPrints/ColorOnly.cshtml
@model WebApp.ViewModels.SearchViewModel
@using WebApp.Services.Utilities
@{
    var pageCount = (Model.FoundCount + 30 - 1) / 30;
    ViewData["Title"] = "Art Prints Matching " + Model.ColorName;
    ViewData["PageTitle"] = "Art Prints Matching " + Model.ColorName;
    ViewData["PageDesc"] = "These art prints are found to contain " + Model.ColorName + " or a color very close to it.";
    ViewData["Type"] = "product.group";

    var images = new List<string>();

    foreach (var r in Model.Results)
    {
        images.Add(r.LargeImageURL);
    }

    var colorURL = Slug.Create(true, Model.ColorName);
    ViewData["Images"] = images;
}

@Html.Partial("_ResultsHeader")
<div id="results">

    @{ await Html.RenderPartialAsync("_Products", Model.Results); }

    @*<div id="results"></div>
        <button id="get-more">Load More</button>
        <a asp-controller="Search" asp-action="Index" asp-route-keywords="@Model.SearchKeywords" asp-route-color="@Model.SearchColor" asp-route-page="@(Model.CurrentPage + 1)">Next Page</a>*@
    @if (Model.FoundCount > 30)
    {
        <div class="row">
            <div class="col-xs-12 col-md-6 col-xl-4">
                @if (Model.CurrentPage != 1)
                {
                    <div class="card next-page-card">
                        <a class="next-page" asp-controller="ArtPrints" asp-action="ColorOnly" asp-route-color="@Model.SearchColor" asp-route-colorname="@colorURL" asp-route-page="@(Model.CurrentPage - 1)" aria-label="Previous"><i class="fa fa-chevron-left left"></i> Previous Page</a>
                    </div>
                }
            </div>
            <div class="col-xs-12 col-md-6 col-xl-4 col-xl-offset-4">
                @if (Model.CurrentPage != pageCount)
                {
                    <div class="card next-page-card">
                        <a class="next-page" asp-controller="ArtPrints" asp-action="ColorOnly" asp-route-color="@Model.SearchColor" asp-route-colorname="@colorURL" asp-route-page="@(Model.CurrentPage + 1)" aria-label="Next">Next Page <i class="fa fa-chevron-right right"></i></a>
                    </div>
                }
            </div>
        </div>
        <nav class="pager-bottom">
            <div style="width: 100%; text-align: center; margin-bottom: -10px;">Jump to Page </div>
            <ul class="pagination pagination-lg">
                @for (int i = 1; i <= pageCount && i < 3335; i++)
                {
                    <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                        <a class="page-link" asp-controller="ArtPrints" asp-action="ColorOnly" asp-route-color="@Model.SearchColor" asp-route-colorname="@colorURL" asp-route-page="@i" aria-label="Page @i">@i</a>
                    </li>
                }
            </ul>
        </nav>
    }
</div>
<div class="clearfix"></div>
@Html.Partial("_Ads")
<div class="p-a-3">
    <a data-sumome-discover-grid></a>
</div>


@section scripts
{
    @Html.Partial("_ProductsScripts");
    @*<script>
            var nextPage = 2;
            $(function () {
                $("#get-more").click(function () {
                    $.get("/Search/_NextResults",
                    {
                        query: '',
                        page: nextPage
                    }, function (data) {
                        $('#results').append(data);
                        nextPage++;
                    })

                });
            })
        </script>*@

}

src/WebApp/Views/ArtPrints/Search.cshtml
@model WebApp.ViewModels.SearchViewModel
@using WebApp.Services.Utilities
@{
    var pageCount = (Model.FoundCount + 30 - 1) / 30;
    ViewData["Title"] = "Search Results";
    ViewData["PageTitle"] = "Search Results";
    ViewData["PageDesc"] = "Search results for a user generated query";
    ViewData["NoIndex"] = true;
    ViewData["Type"] = "product.group";

    var images = new List<string>();

    foreach (var r in Model.Results)
    {
        images.Add(r.LargeImageURL);
    }

    var colorSlug = Slug.Create(true, Model.ColorName);
    var keywordsSlug = Slug.Create(true, Model.SearchKeywords);


    ViewData["Images"] = images;
}

@Html.Partial("_ResultsHeader")

@{ await Html.RenderPartialAsync("_Products", Model.Results); }

@if (Model.FoundCount > 30)
{
    <div class="row">
        <div class="col-xs-12 col-md-6 col-xl-4">
            @if (Model.CurrentPage != 1)
            {
                <div class="card next-page-card">
                    <a class="next-page" asp-controller="ArtPrints" asp-action="Search" asp-route-color="@Model.SearchColor" asp-route-colorname="@colorSlug" asp-route-keywords="@keywordsSlug" asp-route-page="@(Model.CurrentPage - 1)" aria-label="Previous"><i class="fa fa-chevron-left left"></i> Previous Page</a>
                </div>
            }
        </div>
        <div class="col-xs-12 col-md-6 col-xl-4 col-xl-offset-4">
            @if (Model.CurrentPage != pageCount)
            {
                <div class="card next-page-card">
                    <a class="next-page" asp-controller="ArtPrints" asp-action="Search" asp-route-color="@Model.SearchColor" asp-route-colorname="@colorSlug" asp-route-keywords="@keywordsSlug" asp-route-page="@(Model.CurrentPage + 1)" aria-label="Next">Next Page <i class="fa fa-chevron-right right"></i></a>
                </div>
            }
        </div>
    </div>
    <nav class="pager-bottom">
        <div style="width: 100%; text-align: center; margin-bottom: -10px;">Jump to Page </div>
        <ul class="pagination pagination-lg">
            @for (int i = 1; i <= pageCount && i < 3335; i++)
                {
                <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                    <a class="page-link" asp-controller="ArtPrints" asp-action="Search" asp-route-color="@Model.SearchColor" asp-route-colorname="@colorSlug" asp-route-keywords="@keywordsSlug" asp-route-page="@i" aria-label="Page @i">@i</a>
                </li>
            }
        </ul>
    </nav>
}
<div class="clearfix"></div>
@Html.Partial("_Ads")
<div class="p-a-3">
    <a data-sumome-discover-grid></a>
</div>

@section scripts
{
    @Html.Partial("_ProductsScripts");

    @*<script>
            var nextPage = 2;
            $(function () {
                $("#get-more").click(function () {
                    $.get("/Search/_NextResults",
                    {
                        query: '',
                        page: nextPage
                    }, function (data) {
                        $('#results').append(data);
                        nextPage++;
                    })

                });
            })
        </script>*@

}

src/WebApp/Views/ArtPrints/_NextResults.cshtml
@model List<WebApp.Models.ProductSearchResult>

@foreach (var prod in Model)
{
    @if (!String.IsNullOrEmpty(prod.SmallImageURL))
    {
        <img src="@prod.SmallImageURL" />

    }
}
@*<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AffiliateURL)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAdded)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateUpdated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IndependentArtist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AffiliateURL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateAdded)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateUpdated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IndependentArtist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ProductID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ProductID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ProductID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>*@

src/WebApp/Views/ArtPrints/_ProductsPager.cshtml
@model WebApp.ViewModels.SearchViewModel
@{
    var pageCount = (Model.FoundCount + 30 - 1) / 30;
}
@if (Model.FoundCount > 30)
{
    <nav>
        <ul class="pagination pagination-lg">
            @if (Model.CurrentPage != 1)
            {
                <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
                    <a class="page-link" asp-controller="ArtPrints" asp-action="ColorOnly" asp-route-color="@Model.SearchColor" asp-route-colorname="@Model.ColorName" asp-route-page="@(Model.CurrentPage - 1)" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                </li>
            }
            @for (int i = 1; i <= pageCount; i++)
            {
                <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                    <a class="page-link" asp-controller="ArtPrints" asp-action="ColorOnly" asp-route-color="@Model.SearchColor" asp-route-colorname="@Model.ColorName" asp-route-page="@i" aria-label="Page @i">@i</a>
                </li>
            }
            @if (Model.CurrentPage != pageCount)
            {
                <li class="page-item @(Model.CurrentPage == pageCount ? "disabled" : "")">
                    <a class="page-link" asp-controller="ArtPrints" asp-action="ColorOnly" asp-route-color="@Model.SearchColor" asp-route-colorname="@Model.ColorName" asp-route-page="@(Model.CurrentPage + 1)" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
                </li>
            }
        </ul>
    </nav>
}